{% set version = "1.5.2" %}

package:
  name: lazy-object-proxy
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/l/lazy-object-proxy/lazy-object-proxy-{{ version }}.tar.gz
  sha256: 5944a9b95e97de1980c65f03b79b356f30a43de48682b8bdd90aa5089f0ec1f4

build:
  number: 1
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - {{ compiler('c') }}
  host:
    - python
    - pip
    - setuptools_scm >=3.3.1
  run:
    - python

test:
  imports:
    - lazy_object_proxy
    - lazy_object_proxy.cext  # [python_impl != "pypy"]

about:
  home: https://github.com/ionelmc/python-lazy-object-proxy
  license: BSD-2-Clause
  license_file: LICENSE
  summary: A fast and thorough lazy object proxy
  doc_url: https://python-lazy-object-proxy.readthedocs.org
  doc_source_url: https://github.com/ionelmc/python-lazy-object-proxy/blob/master/docs/index.rst
  dev_url: https://github.com/ionelmc/python-lazy-object-proxy

extra:
  recipe-maintainers:
    - jakirkham
    - nehaljwani
    - ocefpaf
    - xylar
