{% set version = "1.12.0" %}

package:
  name: lazy-object-proxy
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/l/lazy-object-proxy/lazy_object_proxy-{{ version }}.tar.gz
  sha256: 1f5a462d92fd0cfb82f1fab28b51bfb209fabbe6aabf7f0d51472c0c124c0c61

build:
  number: 1
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
  host:
    - python
    - pip
    - setuptools >=80
    - setuptools_scm >=8
  run:
    - python

test:
  imports:
    - lazy_object_proxy
    - lazy_object_proxy.cext  # [python_impl != "pypy"]

about:
  home: https://github.com/ionelmc/python-lazy-object-proxy
  license: BSD-2-Clause
  license_file: LICENSE
  summary: A fast and thorough lazy object proxy
  doc_url: https://python-lazy-object-proxy.readthedocs.org
  doc_source_url: https://github.com/ionelmc/python-lazy-object-proxy/blob/master/docs/index.rst
  dev_url: https://github.com/ionelmc/python-lazy-object-proxy

extra:
  recipe-maintainers:
    - jakirkham
    - nehaljwani
    - ocefpaf
    - xylar
